# Generated by Django 4.0 on 2021-12-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_meetup_date_meetup_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='email',
            new_name='organiser_email',
        ),
    ]
